# main configurations
background-opacity = 1
font-family = RobotoMono Nerd Font
font-size = 14
scrollback-limit = 10000000
cursor-style = bar

# color scheme
background = 1d1f21
foreground = c5c8c6
cursor-color = c5c8c6
selection-background = 373b41
selection-foreground = c5c8c6

# colors ANSI (0-15)
palette = 0=#1d1f21
palette = 1=#cc6666
palette = 2=#b5bd68
palette = 3=#f0c674
palette = 4=#81a2be
palette = 5=#b294bb
palette = 6=#8abeb7
palette = 7=#c5c8c6
palette = 8=#969896
palette = 9=#cc6666
palette = 10=#b5bd68
palette = 11=#f0c674
palette = 12=#81a2be
palette = 13=#b294bb
palette = 14=#8abeb7
palette = 15=#ffffff

# vim-style navigation between tabs
keybind = cmd+t=new_tab
keybind = cmd+w=close_surface
keybind = cmd+l=next_tab
keybind = cmd+h=previous_tab

# resize the active split
keybind = ctrl+shift+left=resize_split:left,40
keybind = ctrl+shift+right=resize_split:right,40
keybind = ctrl+shift+up=resize_split:up,40
keybind = ctrl+shift+down=resize_split:down,40
keybind = ctrl+shift+home=equalize_splits

# vim-style navigation between splits
keybind = ctrl+shift+s=new_split:right
keybind = ctrl+shift+q=close_surface
keybind = ctrl+shift+h=goto_split:left
keybind = ctrl+shift+l=goto_split:right
keybind = ctrl+shift+k=goto_split:up
keybind = ctrl+shift+j=goto_split:down

# maximize / minimize font
keybind = ctrl+shift+plus=increase_font_size:1
keybind = ctrl+shift+minus=decrease_font_size:1
keybind = ctrl+shift+zero=reset_font_size
